# Site settings
email:            "allenhurff@gmail.com"
baseurl:          ""
paginate:         5
paginate_path:    "/blog/page-:num"
google_analytics:

# SEO settings
title:            Hurffcraft
description:      Allen Turner Hurff II, aka ATHII, a digital craftsmen. The personal musings, internal thought process, delusions, insights, art, epigrams, failures up, tangble wisdom, but mostly tengential thinking often told backwards that makes me, me ;) I AM gladly Allen Turner Hurff II <3  I might as well BE cause everyone else is taken.
url:              https://allenhurff.com
twitter_username: allenhurff
default_img:

# Profile settings
name:             Allen Turner Hurff II
profile_img:      https://pbs.twimg.com/profile_images/727109991425929216/Y-qg53WX_400x400.jpg # https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
profile:
social:
  github:         https://github.com/allenhurff/allenhurff.github.io
  twitter:        https://twitter.com/allenhurff
  linkedin:       https://www.linkedin.com/in/ahurff/
  youtube:        https://www.youtube.com/channel/UCuvKnCoAVTSik9fK94lbnjA
  instagram:      https://instagram.com/allenhurff

# Build settings
exclude:          ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown:         kramdown
permalink:        /:year/:month/:day/:title/

# Sass
sass:
  style:          compressed

# Gems
gems:             [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
